export const fakeCompany = [
  {
    id: 0,
    companyName: 'Название компании',
    address: 'Адрес',
  },
  {
    id: 1,
    companyName: 'Ашан',
    address: 'г. Москва, ул. Московская, д. 150',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
      {
        id: 20,
        firstName: 'Reta',
        lastName: 'Corkery',
        post: 'Работник № 20',
      },
      {
        id: 21,
        firstName: 'Delta',
        lastName: 'Terry',
        post: 'Работник № 21',
      },
      {
        id: 22,
        firstName: 'Annamarie',
        lastName: 'Smitham',
        post: 'Работник № 22',
      },
      {
        id: 23,
        firstName: 'Tianna',
        lastName: 'Mitchell',
        post: 'Работник № 23',
      },
      {
        id: 24,
        firstName: 'Euna',
        lastName: "O'Hara",
        post: 'Работник № 24',
      },
      {
        id: 25,
        firstName: 'Holly',
        lastName: 'Zulauf',
        post: 'Работник № 25',
      },
    ],
  },
  {
    id: 2,
    companyName: 'Лукойл',
    address: 'г. Москва, ул. Московская, д. 151',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
    ],
  },
  {
    id: 3,
    companyName: 'Сургутнефтегаз',
    address: 'г. Москва, ул. Московская, д. 152',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
    ],
  },
  {
    id: 4,
    companyName: 'X5 Group',
    address: 'г. Москва, ул. Московская, д. 153',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
    ],
  },
  {
    id: 5,
    companyName: 'Татнефть',
    address: 'г. Москва, ул. Московская, д. 154',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
    ],
  },
  {
    id: 6,
    companyName: 'Новатэк',
    address: 'г. Москва, ул. Московская, д. 155',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
    ],
  },
  {
    id: 7,
    companyName: 'НЛМК',
    address: 'г. Москва, ул. Московская, д. 156',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
    ],
  },
  {
    id: 8,
    companyName: 'Северсталь',
    address: 'г. Москва, ул. Московская, д. 157',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
    ],
  },
  {
    id: 9,
    companyName: 'ММК',
    address: 'г. Москва, ул. Московская, д. 158',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
      {
        id: 20,
        firstName: 'Reta',
        lastName: 'Corkery',
        post: 'Работник № 20',
      },
    ],
  },
  {
    id: 10,
    companyName: 'СУЭК',
    address: 'г. Москва, ул. Московская, д. 159',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
    ],
  },
  {
    id: 11,
    companyName: 'МТС',
    address: 'г. Москва, ул. Московская, д. 160',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
    ],
  },
  {
    id: 12,
    companyName: 'Лента',
    address: 'г. Москва, ул. Московская, д. 161',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
    ],
  },
  {
    id: 13,
    companyName: 'Еврохим',
    address: 'г. Москва, ул. Московская, д. 162',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
    ],
  },
  {
    id: 14,
    companyName: 'Мегафон',
    address: 'г. Москва, ул. Московская, д. 163',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
    ],
  },
  {
    id: 15,
    companyName: 'Теле 2',
    address: 'г. Москва, ул. Московская, д. 164',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
    ],
  },
  {
    id: 16,
    companyName: 'Билайн',
    address: 'г. Москва, ул. Московская, д. 165',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
    ],
  },
  {
    id: 17,
    companyName: 'Yota',
    address: 'г. Москва, ул. Московская, д. 166',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
    ],
  },
  {
    id: 18,
    companyName: 'Сбер',
    address: 'г. Москва, ул. Московская, д. 167',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
      {
        id: 20,
        firstName: 'Reta',
        lastName: 'Corkery',
        post: 'Работник № 20',
      },
    ],
  },
  {
    id: 19,
    companyName: 'Альфа-банк',
    address: 'г. Москва, ул. Московская, д. 168',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
    ],
  },
  {
    id: 20,
    companyName: 'Дикси',
    address: 'г. Москва, ул. Московская, д. 169',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
    ],
  },
  {
    id: 21,
    companyName: 'DNS',
    address: 'г. Москва, ул. Московская, д. 170',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
    ],
  },
  {
    id: 22,
    companyName: 'ТМК',
    address: 'г. Москва, ул. Московская, д. 171',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
    ],
  },
  {
    id: 23,
    companyName: 'Мечел',
    address: 'г. Москва, ул. Московская, д. 172',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
    ],
  },
  {
    id: 24,
    companyName: 'Пятерочка',
    address: 'г. Москва, ул. Московская, д. 173',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
      {
        id: 16,
        firstName: 'Rick',
        lastName: 'Mosciski',
        post: 'Работник № 16',
      },
      {
        id: 17,
        firstName: 'Beau',
        lastName: 'Spinka',
        post: 'Работник № 17',
      },
      {
        id: 18,
        firstName: 'Aurelio',
        lastName: 'Bogan',
        post: 'Работник № 18',
      },
      {
        id: 19,
        firstName: 'Nola',
        lastName: 'Kiehn',
        post: 'Работник № 19',
      },
      {
        id: 20,
        firstName: 'Reta',
        lastName: 'Corkery',
        post: 'Работник № 20',
      },
    ],
  },
  {
    id: 25,
    companyName: 'US Rusal',
    address: 'г. Москва, ул. Московская, д. 174',
    staff: [
      {
        id: 0,
        firstName: 'Имя',
        lastName: 'Фамилия',
        post: 'Должность',
      },
      {
        id: 1,
        firstName: 'Melvina',
        lastName: 'Eichmann',
        post: 'Работник № 1',
      },
      {
        id: 2,
        firstName: 'Michael',
        lastName: "O'Kon",
        post: 'Работник № 2',
      },
      {
        id: 3,
        firstName: 'Muhammad',
        lastName: 'Gulgowski',
        post: 'Работник № 3',
      },
      {
        id: 4,
        firstName: 'Kristofer',
        lastName: 'Rohan',
        post: 'Работник № 4',
      },
      {
        id: 5,
        firstName: 'Nathan',
        lastName: 'Sipes',
        post: 'Работник № 5',
      },
      {
        id: 6,
        firstName: 'Florencio',
        lastName: 'Braun',
        post: 'Работник № 6',
      },
      {
        id: 7,
        firstName: 'Lou',
        lastName: 'Bauch',
        post: 'Работник № 7',
      },
      {
        id: 8,
        firstName: 'Desiree',
        lastName: 'Harber',
        post: 'Работник № 8',
      },
      {
        id: 9,
        firstName: 'Anita',
        lastName: 'Strosin',
        post: 'Работник № 9',
      },
      {
        id: 10,
        firstName: 'Era',
        lastName: 'Batz',
        post: 'Работник № 10',
      },
      {
        id: 11,
        firstName: 'Anderson',
        lastName: 'Buckridge',
        post: 'Работник № 11',
      },
      {
        id: 12,
        firstName: 'Aracely',
        lastName: 'Larkin',
        post: 'Работник № 12',
      },
      {
        id: 13,
        firstName: 'Stone',
        lastName: 'Carroll',
        post: 'Работник № 13',
      },
      {
        id: 14,
        firstName: 'Lowell',
        lastName: 'Kozey',
        post: 'Работник № 14',
      },
      {
        id: 15,
        firstName: 'Blanche',
        lastName: 'Hahn',
        post: 'Работник № 15',
      },
    ],
  },
];
